language: erlang
notifications:
  email: false
otp_release:
  - 18.1
  - 17.4

before_script:
  - make version

before_deploy:
  - make package

deploy:
  provider: releases
  api_key: a7713e028cc0f4f1c4fcd4ddb641dc14bddb3ed2
  file: "ez/rabbitmq_arguments_to_headers_exchange-3.5.6.ez"
  skip_cleanup: true
#  on:
#    tags: true