language: erlang
notifications:
  email: false
otp_release:
  - 18.1
  - 17.4

before_script:
  - make version

before_deploy:
  - make package

deploy:
  provider: releases
  api_key: b5122be5bcb21c059e6719ce2954e4aa247f38d0
  file: "ez/rabbitmq_arguments_to_headers_exchange-3.5.6.ez"
  skip_cleanup: true
#  on:
#    tags: true