language: erlang
notifications:
  email: false
otp_release:
  - 18.2
  - 18.1
  - 17.4

before_script:
  - make version
  - make deps

before_deploy:
  - make package

deploy:
  provider: releases
  api_key:
    secure: Ue1xY5HtuWdU+8EuOp8/gIG/wWCpOmbRsIPSzMI6M9YdUZMH5z1ErrH6UkSlYhUPWNEhldnhTZbfH3DMScOntxEeufNGEc+pizm42aN0KxOJktBNiG5kXKh7Nw23QvXfTSXAAhaE7uEnS4VcDm7yKpvYLTSt3XyzPCDZpqwyCPDmGXC/rdHzzdEaswgDsLQvHCyMd6k4m82Z3zkKiVlCI4cNsXO8er4ZgOIt3HqcUK4a/DOgo/v6j9K3WhstGEolH8IJvd53N86llWy4CEEGUVDMrOCmNLq3P7Zmd9N26V7bfF1ppqsNdTU0xf1CEz5ZikNZB4m58FYKDnjn3S3uoxjSjOla+YzVYZ3eI2IXaK8VsOpOMAh1eDmHy0DAwkjcLNDXrgvYlICvSwmrsgNdf4B4QdF3HEta4oc/Cdlgo2VttSS1qPuD93axZ3tFNxCEPl4aMWyVecjpt1d06PQRLei8Uzm4Z+HTpuiFki2mrS1tEcQJuG/nXmgANDzgZ7TZep0KQkLUkoCmDllBn3ORKIHxNk4eyyBL23+Jaw8fgk2SAInWBSgB3nOnkl7jXcUo4G2JHBmSq88/MTdGDkrSrIExrc32p6U3jqxcIJH/p8UrcfG6xBgCAQoQpNv15TT3JdcWgQ2crhEFmjgT4OmRdXTEM1CMtppEMhsWO/PTBs0=
  file: ez/rabbitmq_arguments_to_headers_exchange-3.6.0.ez
  skip_cleanup: true
  on:
    tags: true
